# fly.toml app configuration file generated for chatroom-app on 2024-08-25T02:48:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatroom-app'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
